// Generated by gencpp from file robot_vision/OutpostDetected.msg
// DO NOT EDIT!


#ifndef ROBOT_VISION_MESSAGE_OUTPOSTDETECTED_H
#define ROBOT_VISION_MESSAGE_OUTPOSTDETECTED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include "roboPos.h"

namespace robot_vision
{
template <class ContainerAllocator>
struct OutpostDetected_
{
  typedef OutpostDetected_<ContainerAllocator> Type;

  OutpostDetected_()
    : header()
    , size(0)
    , robotPosArray()  {
    }
  OutpostDetected_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , size(0)
    , robotPosArray(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _size_type;
  _size_type size;

   typedef std::vector< ::robot_vision::roboPos_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robot_vision::roboPos_<ContainerAllocator> >::other >  _robotPosArray_type;
  _robotPosArray_type robotPosArray;





  typedef boost::shared_ptr< ::robot_vision::OutpostDetected_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_vision::OutpostDetected_<ContainerAllocator> const> ConstPtr;

}; // struct OutpostDetected_

typedef ::robot_vision::OutpostDetected_<std::allocator<void> > OutpostDetected;

typedef boost::shared_ptr< ::robot_vision::OutpostDetected > OutpostDetectedPtr;
typedef boost::shared_ptr< ::robot_vision::OutpostDetected const> OutpostDetectedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_vision::OutpostDetected_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_vision::OutpostDetected_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_vision::OutpostDetected_<ContainerAllocator1> & lhs, const ::robot_vision::OutpostDetected_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.size == rhs.size &&
    lhs.robotPosArray == rhs.robotPosArray;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_vision::OutpostDetected_<ContainerAllocator1> & lhs, const ::robot_vision::OutpostDetected_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_vision::OutpostDetected_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_vision::OutpostDetected_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_vision::OutpostDetected_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_vision::OutpostDetected_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_vision::OutpostDetected_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_vision::OutpostDetected_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_vision::OutpostDetected_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42669ca4bebf57ff3133b3571c806e01";
  }

  static const char* value(const ::robot_vision::OutpostDetected_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42669ca4bebf57ffULL;
  static const uint64_t static_value2 = 0x3133b3571c806e01ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_vision::OutpostDetected_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_vision/OutpostDetected";
  }

  static const char* value(const ::robot_vision::OutpostDetected_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_vision::OutpostDetected_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 size\n"
"robot_vision/roboPos[] robotPosArray\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: robot_vision/roboPos\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::robot_vision::OutpostDetected_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_vision::OutpostDetected_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.size);
      stream.next(m.robotPosArray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OutpostDetected_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_vision::OutpostDetected_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_vision::OutpostDetected_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.size);
    s << indent << "robotPosArray[]" << std::endl;
    for (size_t i = 0; i < v.robotPosArray.size(); ++i)
    {
      s << indent << "  robotPosArray[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robot_vision::roboPos_<ContainerAllocator> >::stream(s, indent + "    ", v.robotPosArray[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_VISION_MESSAGE_OUTPOSTDETECTED_H
